### ISSUE TITLE
Different error when doing `ant dist`

### ISSUE THREAD

**Issue by monoxane** [WeTheInternet/collide#5]
when running `ant dist` I get the following error

```
monoxane@tam1:~/collide$ ant dist
Buildfile: /home/monoxane/collide/build.xml

BUILD FAILED
/home/monoxane/collide/build.xml:5: Cannot find /opt/collide/macros.ant.xml imported from /home/monoxane/collide/build.xml

Total time: 0 seconds
```
Running Debian 8, OpenJDK 7u131-2.6.9-2~deb8u1

**Comment by JamesXNelson** [comment]
Hi.

My apologies, I've ripped out all the ant and moved to gradle.  Once I get new jars pushed to central, you should be able to pull it and build simply locally.

I am... kind of hijacking big parts of the IDE (leaving old code in place), to handle a couple DSLs I maintain (a layered text markup language, and a code-generator DSL which extends java w/ xml-like, json-like and css-like expression syntax).  So, my time is kinda split between "make it so other people can run it" and "build the next thing needed to launch other projects". :-/

If you are still interested in getting up and running, please let me know and I'll try to block off a couple hours to release jars and make sure everything builds on a clean box.

**Comment by SeunMatt** [comment]
I am still interested. I tried running the gradle build task even that failed due to dependency resolution. Please, I am interested in not just getting the jars and possibly how to build it as well be it gradle/ant.

Thanks

**Comment by JamesXNelson** [comment]
Ok, cool.  I am presenting at gwtcon this september, and I will definitely have everything necessary to build reproducibly pushed to maven central before then.  Some colleagues and I are going to start a GWT contract services company, and will likely be maintaining our own fork of the 2.X line (my fork give or take a few patches).  

There will be no ant; I build entirely from gradle.  As it is, it works against the HEAD of my gwt fork as well as my framework xapi.  I'm going to do a release of both of them so that my demo for the con will compile and run for anyone who wants to play with it (and then collide will, by proxy, also be simple for others to build).

My apologies on the delays; starting up a company while being a new parent leads to slipping deadlines for side projects. :-)

**Comment by SeunMatt** [comment]
Well, Congrats @JamesXNelson I certainly look forward to being a parent as well one day. Just kindly keep us posted. I actually want to integrate it into our training scheme we are running at [Prodsetrs Learning](https://prodsters.com/learning) to facilitate real-time collaborative coding.
